### ISSUE TITLE
firefox flags site for security risk

### ISSUE THREAD

**Issue by pricelessbrewing** [brewcomputer/brewcomputer-app#4]
FYI @superroma @krutilin 

![image](https://user-images.githubusercontent.com/8812533/120552553-0381b700-c3bd-11eb-8840-6ac576551072.png)

**Comment by superroma** [comment]
some problems with root domain redirect. Will change a link to https://www.brewcomputer.com for now

https://brewcomputer.com - problems
https://www.brewcomputer.com - no problems

**Comment by krutilin** [comment]
We fixed this issue with redirect to www.
